document.getElementById('buket_presi')
document.getElementById('buket_surgo')
document.getElementById('buket_surrs')
document.getElementById('buket_gabin')
document.getElementById('buket_rbmlqi')
document.getElementById('buket_coger')
document.getElementById('buket_ouvid')
document.getElementById('buket_profe')
document.getElementById('buket_audin')
document.getElementById('buket_dimci')
document.getElementById('buket_dplan')
document.getElementById('buket_diraf')
document.getElementById('buket_dconf')
document.getElementById('buket_dimel')
document.getElementById('buket_dimav')
document.getElementById('buket_cgcom')
document.getElementById('buket_ctinf')
document.getElementById('buket_caint')
document.getElementById('buket_cgcre')
document.getElementById('buket_cored')

const card_sector = document.getElementById('card-sector')
const card_profile = document.getElementById('card-profile_photo')
const card_name = document.getElementById('card-name')
const card_place = document.getElementById('card-place')
const card_description = document.getElementById('card-description')
const card_email = document.getElementById('card-email')
const card_curriculum = document.getElementById('card-curriculum')

